[package]
name = "minigrepyay"
version = "0.1.0"
authors = ["Hongchao Liu <lbs.lhc@gmail.com>"]
description = "very dumb grep, as taught in the Rust Programming Language"
edition = "2018"
license = "MIT"

[dependencies]
